### ISSUE TITLE
What is the licence ?

### ISSUE THREAD

**Issue by MathieuAvila** [perandersson/glmock#1]
I'd like to use it in a GPLv2 project. What is the licence for glmock ?

Thank you,

**Comment by perandersson** [comment]
I haven't set a license for this project, so it's basically "you can do whatever you want at your own risk". The project itself is really old and not up-to-date and I do not have the time for doing any work on it at the moment. The only reason for the repository's existence is so that other developers, like yourself, can see the code, read it and do what they want with it at their own risk. 

I other words, feel free to use it in your GPLv2 project
